In [1]:
import numpy as np
import scipy
from scipy.optimize import minimize
import matplotlib.pyplot as plt
from scipy import meshgrid

Find two positive numbers whose sum is 300 and whose product is a maximum

In [2]:
obj_func1 = lambda x: x[0]*x[1]
cons1 = ({'type':'eq','fun': lambda x: x[0] + x[1] - 300}) #remember that x[0]+x[1] = 300 and the constraint should be in the form of constraint >= 0
bnds1 = ((0,None),(0,None)) #because x[0] i.e. x and x[1] i.e. y are both positive
sol1 = minimize(lambda x: -obj_func1(x),(1,1), constraints = cons1, bounds = bnds1) #bad operand error is the result of calling the function without adding the x in parantheses. To find out why
sol1.x

array([150., 150.])

We have 45 m2 of material to build a box with a square base and no top. Determine the dimensions of the box that will maximize the enclosed volume. 

In [3]:
obj_func2 = lambda x: x[0]**2 * x[1]
cons2 = ({'type':'ineq', 'fun': lambda x: -x[0]**2 - 4*x[0]*x[1] + 45})
bnds2 = ((0,None),(0,None))
sol2 = minimize (lambda x: -obj_func2(x),(5,6),constraints = cons2,bounds = bnds2)
sol2.x

array([3.87298608, 1.93648891])

We want to build a box whose base length is 6 times the base width and the box will enclose $ 20 in^3$. The cost of the material of the sides is \\$3/$in^2$ and the cost of the top and bottom is \\$15/$in^2$. Determine the dimensions of the box that will minimize the cost.

In [4]:
obj_func3 = lambda x: 180*x[0]**2 + 42*x[0]*x[1]
cons3 = ({'type':'eq', 'fun': lambda x: 6*(x[0]**2)*x[1] - 20})
sol3 = minimize(obj_func3,(10,2), constraints = cons3 , bounds = ((0,None),(0,None)))
print('Width: {}, Length: {}, Height: {}'.format(sol3.x[0],6*sol3.x[0],sol3.x[1]))

Width: 0.7299210398453896, Length: 4.379526239072337, Height: 6.2564356241843795


We want to construct a cylindrical can with a bottom but no top that will have a volume of $30 cm^3$. Determine the dimensions of the can that will minimize the amount of material needed to construct the can

In [5]:
obj_func4 = lambda x: 2*np.pi*x[0]*x[1] + np.pi*x[0]**2
cons4 = ({'type': 'eq', 'fun': lambda x: np.pi * x[0]**2 * x[1] - 30})
bnds4 = ((0,None),(0,None))
sol4 = minimize(obj_func4, (1,1), constraints = cons4, bounds = bnds4)
print('Radius: {}, Height: {}'.format(sol4.x[0],sol4.x[1]))

Radius: 2.1215331014096264, Height: 2.1216403052331874


We have a piece of cardboard that is 50 cm by 20 cm and we are going to cut out the corners and fold up the sides to form a box. Determine the height of the box that will give a maximum volume

In [6]:
obj_func5 = lambda x: (50-2*x[0])*(20-2*x[0])*x[0]
#cons5 = ({'type':'ineq' , 'fun': lambda x: 20-2*x[0]})
sol5 = minimize(lambda x: -obj_func5(x), 1)
sol5.x[0]

4.401835129156748

In [7]:
obj_func6 = lambda x: x[0]*x[3]*(x[0]+x[1]+x[2])+x[2]
cons6 = ({'type':'ineq', 'fun': lambda x: x[0]*x[1]*x[2]*x[3] - 25},
         {'type':'eq', 'fun': lambda x: x[0]**2 + x[1]**2 + x[2]**2 + x[3]**2 - 40})
bnds6 = ((1,5),(1,5),(1,5),(1,5))
sol6 = minimize(obj_func6,(1,5,5,1),constraints = cons6,bounds = bnds6)
sol6.x

array([1.        , 4.74299607, 3.82115466, 1.37940764])

maximize and minimize $$f(x,y,z) = x + z $$ subject to <br>
$$ x^2 + y^2 + z^2 = 1 $$

In [8]:
obj_func7 = lambda x: x[0] + x[2]
cons7 = ({'type': 'eq', 'fun': lambda x: x[0]**2+x[1]**2+x[2]**2-1})
sols7 = minimize(obj_func7,(1,1,1),constraints = cons7)
sols7.x

array([-7.07106937e-01, -2.69824564e-06, -7.07106934e-01])

In [9]:
sols8 = minimize(lambda x:-obj_func7(x),(1,1,1),constraints = cons7)
sols8.x

array([ 7.07106784e-01, -9.73630194e-09,  7.07106778e-01])

minimise $$ 3x^2 -2xy $$ <br> subject to:
$$x^2 + 5 \le y$$ <br>
$$x + y \ge 12 $$ <br>
$$y^2 + 4x^2 = 18 $$ <br>
$$x \ge 0 , y \ge 0 $$

In [10]:
obj_func9 = lambda x: 3*x[0]**2 - 2*x[0]*x[1]
const9 = ({'type' : 'ineq', 'fun': lambda x: x[1] - x[0]**2 - 5},
          {'type' : 'ineq', 'fun': lambda x:x[0] + x[1] - 12},
          {'type' : 'eq', 'fun': lambda x:x[1]**2 + 4*x[0]**2 - 18})
bnds9 = ((0,None),(0,None))
sols9 = minimize(obj_func9,(1,1),constraints = const9, bounds = bnds9)
sols9.x

array([0.45319305, 3.0592358 ])

In [25]:
obj_func10 = lambda x: 20*x[0] + 12*x[1] + 40*x[2] + 25*x[3]
const10 = ({'type' : 'ineq' ,'fun': lambda x: 50 - x[0] - x[1] - x[2] - x[3]},
           {'type' : 'ineq' ,'fun': lambda x: 100 - 3*x[0] - 2*x[1] - x[2]},
           {'type' : 'ineq' ,'fun': lambda x: 90 - x[1] - 2 *x[2] - 3*x[3]})
bnds10 = ((0,None),(0,None),(0,None),(0,None))
sols10 = minimize(lambda x: -obj_func10(x), (1,1,1,1), constraints = const10, bounds = bnds10)
sols10

     fun: -1899.9999999932525
     jac: array([-20., -12., -40., -25.])
 message: 'Optimization terminated successfully.'
    nfev: 24
     nit: 4
    njev: 4
  status: 0
 success: True
       x: array([ 5.,  0., 45.,  0.])

In [35]:
def obj_func11(x):
    return -20*x[0] - 12*x[1] - 40*x[2] - 25*x[3]
def cn1(x):
    return 50 - x[0] - x[1] - x[2] - x[3]
def cn2(x):
    return 100 - 3*x[0] - 2*x[1] - x[2]
def cn3(x):
    return 90 - x[1] - 2 *x[2] - 3*x[3]
const11 = ({'type': 'ineq', 'fun': cn1},
           {'type': 'ineq', 'fun': cn2},
           {'type': 'ineq', 'fun': cn3})
sols11 = minimize(obj_func11, (1,1,1,1), constraints = const11, bounds = bnds10)
sols11

     fun: -1899.9999999932525
     jac: array([-20., -12., -40., -25.])
 message: 'Optimization terminated successfully.'
    nfev: 24
     nit: 4
    njev: 4
  status: 0
 success: True
       x: array([ 5.,  0., 45.,  0.])